### ISSUE TITLE
Out of date data. 

### ISSUE THREAD

**Issue by Aduffy** [eparker12/nCoV_tracker#1]
If this data is not kept up o date than the site at https://vac-lshtm.shinyapps.io/ncov_tracker/ should be taken down. Outdated data is almost as bad as false data.

**Comment by eparker12** [comment]
Thank you for raising this query. I can confirm that the site is still being maintained. There was a temporary delay in the latest update (17th March 2020) while the site shifted from using WHO situation reports to the Johns Hopkins timeline data as the primary input. 

The input data are currently updated once daily, and at this time of rapid pandemic escalation the numbers can therefore change significantly between updates. To clarify this, I have added notes on the main mapping page as well as the 'About this site' tab, linking to the Johns Hopkins dashboard in both places.

Please also note that the aim of this site is to provide alternative ways of interacting with the COVID-19 data, including the timeline function, the ability to overlay past epidemics, and the flexible country plotting tab. I defer to the WHO and Johns Hopkins dashboards for the latest numbers.

I trust that this addresses your concerns.
