### ISSUE TITLE
Mapping data lacking for country "MSZaandam"

### ISSUE THREAD

**Issue by eomwandho** [eparker12/nCoV_tracker#3]
I getting the error below when starting the app

> Error: mapping data lacking for the following countries: MSZaandam

![image](https://user-images.githubusercontent.com/2696951/77883253-67659880-726b-11ea-99e3-ac1b18662d11.png)

**Comment by eparker12** [comment]
Thanks for raising this issue. The latest Github updates (specifically the modifications of countried_codes_and_coordinates.csv) should address this issue.

**Comment by eomwandho** [comment]
```Works now! Thanks for the quick fix

**Comment by jurteagat** [comment]
I found a similar error now:
<<<
Error in eval(ei, envir) : 
  Error: mapping data lacking for the following countries: Korea.North
>>>
