### ISSUE TITLE
map is covered by the nav-bar

### ISSUE THREAD

**Issue by rjscherrer** [eparker12/nCoV_tracker#4]
Nice App!

`div.outer {
position: fixed;
  top: 35px;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
  padding: 0;
}`

The nav-bar has a bottom-margin of 21px. If you change the definition above like followed the map gets placed below the nav-bar.

`div.outer {
  position: fixed;
  margin: -21px;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
  padding: 0;
}`

**Comment by eparker12** [comment]
Hi. Thanks for flagging this up. When I try the suggested code in styles.css, unfortunately the map will not render. It seems that 'top: 35px' is required for this, and including 'top: 35px; margin: -21px' does not solve the issue either. Perhaps there is another solution?

**Comment by rjscherrer** [comment]
I did not test it directly in your app, but I use the same page layout and had the same problem. As I mentioned above, the problem is that the navbar has a margin-bottom of 21px (you can see this with the web inspector). Since the navbar class is also .navbar, the following should work like it did for me:

`.navbar {
   margin-bottom: 0 !important;
}`

Make sure to insert this line of code in the right place of your css definitions and that it doesn't come to side effects with other css definitions.

**Comment by eparker12** [comment]
Thanks for following up on this. I managed to fix this by adding 21px to the navbar:

div.outer { position: fixed; top: 56px; left: 0; right: 0; bottom: 0; overflow: hidden; padding: 0; }

Mapping pages are looking much neater as a result. Thanks!
